Added new features and tests.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,10 +5,8 @@ on:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]
-  #    This runs every day at midnight UTC to check for z-core updates
   schedule:
     - cron: '0 0 * * *'
-  # Allows you to click "Run workflow" manually in GitHub Actions tab
   workflow_dispatch:
 
 permissions:
@@ -30,7 +28,6 @@ jobs:
         with:
           python-version: '3.x'
 
-      # Update z-core to the latest commit
       - name: Update z-core submodule
         run: |
           git submodule update --remote --merge
@@ -38,6 +35,30 @@ jobs:
 
       - name: Run Make
         run: make
+
+      - name: Test Z-Scanner
+        run: |
+          echo "Running scanner on examples/..."
+          mkdir -p include
+          
+          python3 z-core/zscanner.py examples/ include/z_registry.h
+          
+          if [ -f "include/z_registry.h" ]; then
+            echo "Scanner successfully generated registry!"
+            cat include/z_registry.h
+          else
+            echo "::error::Scanner failed to generate registry file."
+            exit 1
+          fi
+          rm -rf include 
+
+      - name: Build Library
+        run: make bundle
+
+      - name: Run Unit Tests
+        run: |
+          echo "Running C and C++ Test Suites..."
+          make test || { echo "::error::Unit tests failed! Check the logs above for assertion errors."; exit 1; }
 
       - name: Commit and Push changes
         uses: stefanzweifel/git-auto-commit-action@v5
